// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyahwtwywlhsedsbdntw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5YWh3dHd5d2xoc2Vkc2JkbnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjA1MzYsImV4cCI6MjA2NTMzNjUzNn0.Bk2KMKEPyNnZEeMfQILlkQcN0w5FOh9TuMG3PnYtKIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);